version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - ecommerce

  ecommerce_vue:
    build: ./ecommerce_vue
    volumes:
      - ./ecommerce_vue:/app
      - /app/node_modules
    depends_on:
      - ecommerce

  ecommerce:
    build: ./ecommerce
    volumes:
      - ./ecommerce:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./ecommerce/.env
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 ecommerce.wsgi:application"

volumes:
  static_volume:
  media_volume:
