# Generated by Django 5.0.4 on 2024-04-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
